rng1:
    build: rng
rng2:
    build: rng
rng3:
    build: rng

rng0:
    image: jpetazzo/hamba
    links:
      - rng 1
      - rng 2
      - rng 3
    command: 80 rng1 80 rng2 80 rng3 80
    ports:
      - "8001:80"

hasher:
    build: hasher
    ports:
      - "8002:80"

webui:
    build: webui
    links:
      - redis
    ports:
      - "8000:80"
    volumes:
      - "webui/files/:/files/"
    extra_hosts ... FIXME slides 35-37

redis:
    image: redis

worker:
    build: worker
    links:
      - rng
      - hasher
      - redis

